# Generated by Django 4.1.7 on 2023-03-31 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contas',
            fields=[
                ('id_conta', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=250, unique=True)),
                ('situacao', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name': 'Conta',
                'verbose_name_plural': 'Contas',
                'db_table': 'contas',
                'managed': False,
            },
        ),
    ]
