# Generated by Django 4.1.7 on 2023-03-31 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculos',
            fields=[
                ('id_calculos', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.FloatField()),
                ('publica', models.BooleanField(default=True)),
                ('dt_lancamento', models.DateTimeField()),
                ('mesano', models.CharField(max_length=6)),
            ],
            options={
                'verbose_name': 'Calculo',
                'verbose_name_plural': 'Calculos',
                'db_table': 'calculos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Leituras',
            fields=[
                ('id_leituras', models.AutoField(primary_key=True, serialize=False)),
                ('mesano', models.CharField(max_length=6, verbose_name='MES/ANO')),
                ('dt_leitura', models.DateField()),
                ('vl_gas_m3', models.FloatField()),
                ('leitura_inicial', models.FloatField()),
                ('leitura_final', models.FloatField()),
            ],
            options={
                'verbose_name': 'Leitura',
                'verbose_name_plural': 'Leituras',
                'db_table': 'leituras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movimento',
            fields=[
                ('id_movimento', models.AutoField(primary_key=True, serialize=False)),
                ('mesano', models.CharField(max_length=6)),
                ('valor', models.FloatField()),
                ('dt_lancamento', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Movimento',
                'verbose_name_plural': 'Movimentos',
                'db_table': 'movimento',
                'managed': False,
            },
        ),
    ]
