# Generated by Django 4.1.7 on 2023-03-31 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id_cadastro', models.AutoField(primary_key=True, serialize=False)),
                ('cpf_cnpj', models.CharField(max_length=14, unique=True)),
                ('nome', models.CharField(max_length=250)),
                ('endereco', models.CharField(max_length=250)),
                ('bairro', models.CharField(max_length=250)),
                ('cidade', models.CharField(max_length=250)),
                ('cep', models.CharField(max_length=8)),
                ('situacao', models.CharField(max_length=1)),
                ('dt_registro', models.DateTimeField()),
                ('email', models.CharField(max_length=250)),
                ('telefone', models.CharField(max_length=250)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cadastro',
                'verbose_name_plural': 'Cadastros',
                'db_table': 'cadastro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('uf', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'estado',
                'managed': False,
            },
        ),
    ]
