# Generated by Django 4.1.7 on 2023-03-31 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCalculo',
            fields=[
                ('id_tipo_calculo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=5)),
                ('situacao', models.CharField(max_length=1)),
                ('descricao', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Tipo Calculo',
                'verbose_name_plural': 'Tipo Calculos',
                'db_table': 'tipo_calculo',
                'managed': False,
            },
        ),
    ]
